---
# Install Git
- name: Install Apps
  block:
  - name: Install required packages for Docker
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
      state: latest
      update_cache: true
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true
  - name: Check docker is active
    service:
      name: docker
      state: started
      enabled: yes
  - name: Adding authz to docker group
    user:
      name: authz
      groups: docker
      append: yes
  - name: Install Docker-compose
    apt:
      name:
        - docker-compose
      state: latest
      update_cache: true
  - name: Install ACL (Access control list utilities)
    apt:
      name:
        - acl
      state: latest
      update_cache: true
  become: true
  become_user: root