version: "3.4"
services:
  authz:
    image: authz
    container_name: authz-service
    build: /home/authz/git
    ports:
      - 80:5000
    tty: true
    volumes:
      - Docker_Authz:/home/authz/app
volumes:
  Docker_Authz: