version: "3.4"
services:
  authz:
    image: authz
    container_name: authz-service
    build: /home/authz/git
    ports:
      - 80:5000
    tty: true
    network_mode: host
    volumes:
      - $HOME:/home/authz/app