FROM nginx
COPY /conf/nginx/authz_server.conf /etc/nginx/conf.d
COPY /conf/nginx/nginx.conf /etc/nginx
COPY /conf/sertbot.sh /etc/
RUN chmod 755 /etc/sertbot.sh
# RUN /home/setup-certbot-and-install-ssl-sertificat-script.sh
