FROM ubuntu:22.04
RUN apt update
RUN apt install certbot -y
EXPOSE 80
COPY conf/certbot/certbot.sh /tmp/certbot.sh
COPY conf/certbot/privkey.pem /tmp/privkey.pem
COPY conf/certbot/fullchain.pem /tmp/fullchain.pem
CMD /tmp/certbot.sh