---
# tasks file for service-authz
- name: work with docker
  block:
  - name: Clone master branch
    ansible.builtin.git:
      repo: https://github.com/ESergiusz/dos14-Eremeev-GitFlow.git
      dest: /home/authz/git
      single_branch: yes
      force: yes
      version: feature-hw-25
  - name: Build container (docker-compose)
    community.docker.docker_compose:
      project_src: /home/authz/git
      files:
        - docker-compose.yaml
  become: true
  become_user: authz