---
# tasks file for service-authz
- name: Create folders and copy files
  block:
    - name: Create a directory for nginx logs
      ansible.builtin.file:
        path: /var/log/nginx_logs
        state: directory
        mode: '0755'
    - name: Create a directory for certbot logs
      ansible.builtin.file:
        path: /var/log/certbot_logs
        state: directory
        mode: '0755'
    - name: Create a directory for certbot storage
      ansible.builtin.file:
        path: /etc/letsencrypt
        state: directory
        mode: '0755'
    - name: Create a directory for SSL certificate (certbot)
      ansible.builtin.file:
        path: /etc/letsencrypt/live/esa.authz.smodata.net
        state: directory
        mode: '0755'
    - name: Copy file certbot.sh with owner and permissions
      ansible.builtin.copy:
        src: /conf/certbot/sertbot.sh
        dest: /etc/letsencrypt/sertbot.sh
        owner: root
        group: root
        mode: '0755'
    - name: Copy file fullchain.pem
      ansible.builtin.copy:
        src: /conf/certbot/fullchain.pem
        dest: /etc/letsencrypt/live/esa.authz.smodata.net/fullchain.pem
        owner: root
        group: root
        mode: '0755'
    - name: Copy file privkey.pem
      ansible.builtin.copy:
        src: /conf/certbot/fullchain.pem
        dest: /etc/letsencrypt/live/esa.authz.smodata.net/privkey.pem
        owner: root
        group: root
        mode: '0755'
  become: true
  become_user: root
- name: Work with docker
  block:
  - name: Clone {{ git_branch }} branch
    ansible.builtin.git:
      repo: https://github.com/ESergiusz/dos14-Eremeev-GitFlow.git
      dest: /home/authz/git
      single_branch: yes
      force: yes
      version: "{{ git_branch }}"
  - name: Build container (docker-compose)
    community.docker.docker_compose:
      project_src: /home/authz/git
  become: true
  become_user: authz