---
# tasks file for service-authz
- name: Create folders and copy files
  block:
    - name: Copy file db_login.env
      ansible.builtin.copy:
        src: ./conf/db/db_login.env
        dest: /etc/PGDATA/db_login.env
        owner: root
        group: root
        mode: '0644'
  become: true
  become_user: root
- name: Work with docker
  block:
  - name: Clone {{ git_branch }} branch
    ansible.builtin.git:
      repo: https://github.com/ESergiusz/dos14-Eremeev-GitFlow.git
      dest: /home/authz/git
      single_branch: yes
      force: yes
      version: "{{ git_branch }}"
  - name: Build container (docker-compose)
    community.docker.docker_compose:
      project_src: /home/authz/git
  become: true
  become_user: authz
- name: Delete file
  block:
  - name: Delete db_login.env
    ansible.builtin.file:
      path: /etc/PGDATA/db_login.env
      state: absent
  become: true
  become_user: root