---
# tasks file for service-authz
- name: Create dir and copy files
  block:
    - name: Copy file db_login.env
      ansible.builtin.copy:
        src: ../conf/db/db_login.env
        dest: /tmp/db_login.env
        owner: root
        group: root
        mode: '0644'
  become: true
  become_user: root
- name: Work with docker
  block:
  - name: Clone {{ git_branch }} branch
    ansible.builtin.git:
      repo: https://github.com/ESergiusz/dos14-Eremeev-GitFlow.git
      dest: /home/authz/git
      single_branch: yes
      force: yes
      version: "{{ git_branch }}"
  - name: Encrypt file fullchain.pem
    ansible.builtin.copy:
      src: ../conf/certbot/fullchain.pem
      dest: /home/authz/git/conf/certbot/fullchain_tmp.pem
  - name: Rename fullchain_tmp.pem to fullchain.pem
    command: mv /home/authz/git/conf/certbot/fullchain_tmp.pem /home/authz/git/conf/certbot/fullchain.pem
  - name: Encrypt file privkey.pem
    ansible.builtin.copy:
      src: ../conf/certbot/privkey.pem
      dest: /home/authz/git/conf/certbot/privkey_tmp.pem
  - name: Rename privkey_tmp.pem to privkey.pem
    command: mv /home/authz/git/conf/certbot/privkey_tmp.pem /home/authz/git/conf/certbot/privkey.pem
  - name: Build container (docker-compose)
    community.docker.docker_compose:
      project_src: /home/authz/git
  become: true
  become_user: authz
- name: Delete files
  block:
  - name: Delete db_login.env
    ansible.builtin.file:
      path: /tmp/db_login.env
      state: absent
  become: true
  become_user: root