apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      {{- include "labels" . | indent 6 }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 8 }}
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.nginx.tag }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
      volumes:
      - configMap:
          name: {{ .Values.name }}-nginx-config
        name: nginx-config