apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host.name }}.{{ .Values.host.domain }}
    http:
      paths:
      - path: /authz(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.name }}-svc
            port:
              number: 80
  tls:
    - hosts:
      - {{ .Values.host.name }}.{{ .Values.host.domain }}
      secretName: {{ .Values.host.name }}-tls