apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}-service-account
type: kubernetes.io/service-account-token