apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.labels.app }}
    bank: {{ .Values.labels.bank }}
    env: {{ .Values.labels.env }}