apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 4 }}
automountServiceAccountToken: {{ .Values.serviceaccount.automountServiceAccountToken }}