---
# tasks file run flask
- name: work with poetry
  block:
  - name: Clone master branch
    ansible.builtin.git:
      repo: https://github.com/ESergiusz/dos14-Eremeev-GitFlow.git
      dest: /home/authz/git
      single_branch: yes
      force: yes
      version: master
  - name: Run a command "poetry install"
    ansible.builtin.shell:
      chdir: /home/authz/git
      cmd: poetry install
    args:
      executable: /bin/bash
    changed_when: false
  become: true
  become_user: authz
- name: Run service
  block:
    - name: Create flask service
      ansible.builtin.template:
        src: flask.serviced.j2
        dest: /etc/systemd/system/flask.service
        owner: root
        group: root
        mode: '0755'
  notify:
    - run flask service
    - check start flask service
  become: true
  become_user: root