# !!!!!!   Config DEV environment  !!!!!!!
#
# Config deployment.yaml
deployment:
  image:
    name: esergiusz/dos14-authz
    tag: e1f869db8b0fde2f9ba61887b18a202e82c4d409
  nginx:
    tag: 1.25.3
  spec:
    replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  env:
    name_base: PG_DB
    name_base_value: ivanoffbank
    username_db: PG_USER
    usernameKeyRef:
      username: username
      password: password
      name: ivanoff-db-creds
    password: PG_PASSWORD
    hostname: PG_HOST
    hostname_value: omegabank-rds-tf.cearikylb8tb.eu-west-1.rds.amazonaws.com
    port_name: PG_PORT
    port_value: "5432"
  probes:
    liveness:
      path: /api/v1/authz/health_check
      port: 80
      initialDelaySeconds: 30
      periodSeconds: 3
    readiness:
      path: /api/v1/authz/health_check
      port: 80
      initialDelaySeconds: 30
      periodSeconds: 3
# Config ingress.yaml
ingress:
  host:
    name: ivanoff
    domain: smodata.net
  annotations:
    useregex: \"true\"
    rewritetarget: /$1
  ingressClassName: nginx
  path: /authz(.*)
  pathservice: /authz
# Config service.yaml
service:
  ports:
    protocol: TCP
    port: 80
    targetPort: 80
# Config clusterissuer.yaml
clusterissuer:
  issuerName: letsencrypt-staging
# Config serviceaccount.yaml
serviceaccount:
  automountServiceAccountToken: false